### ISSUE TITLE
General question on lesson workflow and timing

### ISSUE THREAD

**Issue by annefou** [coderefinery/git-in-the-browser#1]
- Title: Why do you say "Almost no command line required". Is command line required at all?

- Apart from the title (see comment above), I like how the lesson is organize with 4 sections (motivations, repo creation, collaboration within the same repo and with fork).

I don't know how non-technical are the attendees so my comments may be irrelevant. But you tell me...
Overall the lesson may be a bit too long (1h30 including time to seat, connect to wifi, etc.).

1.  Introduction and motivation: I understand the logic but starting from "what is a commit" is a bit weird. 
I am probably rather classical here but I would start with:

* What is version control? (and then I like the way you explain snapshots)

* Why version control is important?

* Git and github (and I like how it is explained in the lesson).

I would forget tags and branches in the intro.

2. Creating a repository on GitHub and recording changes

I would forget branches too. I don't think there is enough time to cover this part. But I may be wrong...

3. Collaborating on a project within the same repository

I would work in pairs (that's what we do at UIO and it works pretty well). It is simpler to organize.

4. Collaborating on a project using forks
Important section so we need to make sure enough time is dedicated to this part.

**Comment by bast** [comment]
Thanks for the good points and questions!

About the command line: I have not found a reasonable way of updating a fork that does not involve the command line so if we update forks, this will be the only command line thing we will do but I tested this on Windows and we would all together issue 4 commands.

I am also worried that it is too much stuff for 1.5 hours so I need to remove something and I will. We need to identify the least important part.

I will reorder intro, thanks!

I will drop tags but I would like to keep branches because IMO collaboration within a repo or via forks only reasonably works if you use branches. But here I have a dilemma: most of the "non-technical" persons attending this workshop will only really interact with the NeIC website sources and here if you want to look at the changes before submitting them, you probably have to stay on the same branch. So our most prominent use-case within NeIC is an exception to a relatively general rule. Now I am not sure whether I want to teach how to collaborate on gh-pages or to teach good general practices without confusing people too much.

I agree that I can drop branches in part 2. The idea was to prepare them for part 3 but we can introduce them in part 3.

Good idea about working in pairs.

I will do another iteration but I am unsure about the forking part whether I want to keep it general or tuned to GitHub pages.

**Comment by annefou** [comment]
If most people attending will be updating the NeIC website only (or mostly) and considering the session is quite short, tuning it to GitHub pages sounds like a reasonable approach.

**Comment by bast** [comment]
OK I will do that. I think it makes sense. Initially I wanted something more general and reusable but it's good to have a clear and relevant focus. In this case we may get away without branches, let's see. I will make another iteration on the material and ask for new round of feedback before the concrete solidifies.

**Comment by bast** [comment]
It is very frustrating for me because I don't see how I can make this tutorial work without confusing everybody completely:
- gh-pages example would be relevant
- it would be nice if we could fork and inspect changes on the fork before submitting them
- in order to inspect changes on the fork we have to stay on the gh-pages branch (it is possible to serve the website from either gh-pages branch or master)
- submitting a PR from the same branch either a) introduces a merge commit or b) alters hash of the commit
- this means that if you update your fork, then the forked gh-pages will diverge
- there is apparently no way to submit a later, second PR in a clean way, containing only the new change

So now I have several choices:
- do not show gh-pages example but then it is not relevant for participants
- do not fork but then we have no way of previewing changes unless we have a set up which mirrors another branch to another web service
- advice people to remove their forks after their PR has been accepted - super dangerous, one day somebody will accidentally wipe out our central repo

**Comment by bast** [comment]
To avoid all the hash/merge commit troubles I wanted to always create new branches before doing any work but then we cannot preview them unless we call it master and change settings but that is also really confusing. The branch can be updated in a clean way via command line but this is completely unrealistic to teach in 90 minutes to novices.

**Comment by bast** [comment]
OK it seems it might be doable still (discussion on CodeRefinery slack channel). I will explore more.

**Comment by annefou** [comment]
Yes. I made a few tests too. I think you need to control conflicts as much as possible to be easily sync your fork. This may not be completely realistic but in 90mn what else can you do...

**Comment by bast** [comment]
I will try to stay clear of conflicts by a careful design of the exercise. Thanks for testing. I implemented some of your suggestions but more to follow tonight/tomorrow. I will notify you then.

**Comment by maikenp** [comment]
Hi, 
I am also having a look at the nice tutorial you are making. 

My very few and very minor comments are: 

>Git branches are pointers (labels) to commits. 
Maybe better a *set* of labels? So that one does not confuse and think that a branch is the same as a single pointer/label. 

On this page: https://coderefinery.github.io/git-in-the-browser/03-collaborate-same-repo/ 
Do you call the merged commits m1 and m2 since they represent the merge? Is it an option to instead use c3 and c4, to show that it belongs to the same line? 

Other than that I understand your dilemma about previewing the page. Hope you find a good solution! 

Do you know for sure that the neic gh-pages are the main target for the participants? Did you make a small survey? If yes, then important to really stick to that, if no, a mix, then maybe you can show something a bit more general, that will solve the problem?

**Comment by bast** [comment]
Thanks Maiken for feedback!

A branch is actually one single label but I need to make more clear that it points to a commit and its entire history to the beginning of time.

About m1/m2: I will see how to make that more clear. I wanted to signal that a merge commit is a bit different than a "normal" commit since it has two parents.

I did not survey participants but the confusion around gh-pages and forking workflow was my main motivation to create this tutorial but I will try to strike a good balance to also cater to other use cases. I will rework the material this morning and then share with you the iteration 2.

**Comment by bast** [comment]
@annefou @maikenp - can you please give me new round of feedback? I have implemented hopefully most of your suggestions, also streamlined a bit.

My questions/worries:
- I think it is too much for 90 minutes
- If you had to drop something, what section or part or aspect would you drop?

I know it is very terse, there will be screenshots and more background but I want to do that first once the structure an outline are converged.

Every suggestion most welcome. Thank you!

**Comment by maikenp** [comment]
Yes, will have a look. I had started to comment about the label/pointer question, but I never finished. What I in general meant is that maybe for all practical purposes it is enough to think of a branch as a “line of commits”. I will have a look at the page!

On 26 Jan 2018, at 15:19, Radovan Bast <notifications@github.com<mailto:notifications@github.com>> wrote:


@annefou<https://github.com/annefou> @maikenp<https://github.com/maikenp> - can you please give me new round of feedback? I have implemented hopefully most of your suggestions, also streamlined a bit.

My questions/worries:

  *   I think it is too much for 90 minutes
  *   If you had to drop something, what section or part or aspect would you drop?

I know it is very terse, there will be screenshots and more background but I want to do that first once the structure an outline are converged.

Every suggestion most welcome. Thank you!

**Comment by bast** [comment]
The "line of commits" is a good suggestion. I shall clarify this in the text better.

**Comment by maikenp** [comment]
Timeline: The time for each exercise is almost for sure too little.

But what you can do is that you do everything simultaneously on the screen while people follow. And have a system where people raise there hand or something if you went to the next step and they were not ready. Dont know if this is something that could work. Have you tried it before? Tends to become messy. And to look up and follow instructions, then look down and do it, does not often work so well.

But in general: for the very limited time to work for this tutorial then everything must be super-simplified. Not much room for own testing, just follow instructions. Then they can rather test more after the workshop.

You probably have already thought about all this!
Maiken :)





On 26 Jan 2018, at 15:26, Radovan Bast <notifications@github.com<mailto:notifications@github.com>> wrote:


The "line of commits" is a good suggestion. I shall clarify this in the text better.

**Comment by bast** [comment]
The format will be type-along and interactive. I also think it's too much and the only way to change it is to throw something out. I am thinking of tossing either part 2 or part 3. Which one do you think of the two could be dropped?

**Comment by maikenp** [comment]
I think that if you keep 3 you can work with branches and forks at the same time. Forks are very useful I think. But it depends if the people will do forking on their repo?
On 26 Jan 2018, at 15:47, Radovan Bast <notifications@github.com<mailto:notifications@github.com>> wrote:


The format will be type-along and interactive. I also think it's too much and the only way to change it is to throw something out. I am thinking of tossing either part 2 or part 3. Which one do you think of the two could be dropped?

**Comment by bast** [comment]
I think eventually every project converges to forking. Do you think it is OK if we jump right into collaborative section 3 and drop the part where people play around a bit creating own repos (in other words drop part 2)?

**Comment by annefou** [comment]
Yes! Most of the time you don't create your own repo.
Anne
________________________________________

**Comment by bast** [comment]
OK I am dropping part 2. Thanks!

**Comment by bast** [comment]
I have updated the tutorial and am closing this issue. You are most welcome to review the material and suggest changes. For this please open new issues. It was good to discuss general questions in one issue but from here on in this repo, please open one issue per suggestion/issue, to keep it easier for me to keep track of what remains to be done.
